[package]
name = "futures-black-hole"
description = "Black hole implementation for futures"
version = "0.2.1"
authors = ["Yota Toyama <raviqqe@gmail.com>"]
license = "MIT"

[dependencies]
futures-await = "0.1"
futures-cpupool = "0.1"
