version: 2
jobs:
  build:
    docker:
      - image: rustlang/rust:nightly
    steps:
      - checkout
      - run:
          name: Build
          command: |
            cargo build
            cargo build --release
      - run:
          name: Test
          command: cargo test
